frontend:
  replicaCount: 2
  image:
    repository: chandranavinn/cm2-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8000

backend:
  replicaCount: 2
  image:
    repository: chandranavinn/cm2-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8000
