frontend:
  replicaCount: 2
  image:
    repository: chandranavinn/cm2-frontend
    tag: fc031db858d73916c6fab5790651319224074aad
    pullPolicy: IfNotPresent
  service:
    port: 8000

backend:
  replicaCount: 2
  image:
    repository: chandranavinn/cm2-backend
    tag: fc031db858d73916c6fab5790651319224074aad
    pullPolicy: IfNotPresent
  service:
    port: 8000
