apiVersion: v1
kind: Service
metadata:
  name: cm-backend
  labels:
    app: cm-backend
spec:
  type: ClusterIP
  selector:
    app: cm-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
